apiVersion: v1
kind: Service
metadata:
  name: front-keepguard-core-service
  namespace: keepguard
  labels:
    app: front-keepguard-core
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: front-keepguard-core
