replicaCount: 2

image:
  repository: ghcr.io/keepguard/front-keepguard-core
  pullPolicy: IfNotPresent
  tag: "1.0.0"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  host: app-core.keepguard.com.br
  tlsSecretName: front-keepguard-core-tls

tenantId: "f7fc7350-b9fc-4e54-9c58-ac9385b23ae3"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
